Repository knative-extensions/eventing-istio, pull requests merged in 2023-12, with the labels that each got.

#170 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#173 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#177 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#180 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#187 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#191 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm, skip-review

#192 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm, skip-review

#194 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#196 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm, skip-review

#197 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm, skip-review

#200 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#199 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm, skip-review

#203 Update submodules once before submodules are fetched
  hack/update-deps.sh
Labels: size/XS, approved, lgtm

#206 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#207 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#208 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#209 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#210 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#211 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#212 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review
