Repository knative-extensions/eventing-istio, pull requests merged in 2023-05, with the labels that each got.

#19 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm

#12 Fix ugprade dependencies/submodules script
  hack/update-deps.sh
Labels: approved, size/S, lgtm

#22 Allow setting owner references
  config/eventing-istio/roles/controller-clusterroles.yaml
Labels: approved, size/S, lgtm

#23 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#24 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
