Repository knative-extensions/eventing-istio, pull requests merged in 2023-07, with the labels that each got.

#37 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#33 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/XL, approved, lgtm

#40 Add release script
  hack/release.sh
Labels: approved, size/M, lgtm

#38 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#39 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#41 Fix `REPO_ROOT_DIR` env override in e2e tests
  test/e2e-common.sh
Labels: approved, size/S, lgtm

#44 Use correct path to `hack/build-from-source.sh`
  hack/release.sh
Labels: size/XS, approved, lgtm

#45 Fix setting readonly `TAG` variable
  hack/release.sh
Labels: size/XS, approved, lgtm

#42 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#43 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#46 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#47 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#50 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/S, lgtm

#49 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#48 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#51 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#52 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#53 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#55 Fix update-deps.sh script
  hack/update-deps.sh
Labels: size/XS, approved, lgtm

#59 Move submodule update to git fetch
  hack/update-deps.sh
Labels: size/XS, approved, lgtm
