Repository knative-extensions/eventing-istio, pull requests merged in 2023-11, with the labels that each got.

#138 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#139 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/istio/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/istio/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#143 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#144 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#149 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#148 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#151 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#153 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm

#155 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#161 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, approved, lgtm

#162 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#157 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm

#165 Fix branch name in message of update-deps.sh
  hack/update-deps.sh
Labels: size/XS, approved, lgtm

#168 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#164 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#169 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review
