Repository knative-extensions/eventing-istio, pull requests merged in 2024-04, with the labels that each got.

#300 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#294 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#301 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#302 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#304 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#306 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm, skip-review

#307 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#308 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#309 Only initialize and update submodules when "upgrade" param is given
  hack/update-deps.sh
Labels: approved, size/S, lgtm

#313 Checkout submodule instead of merge changes from origin
  hack/update-deps.sh
Labels: size/XS, approved, lgtm

#323 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#325 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#327 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#305 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: approved, size/L, lgtm, skip-review

#329 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#332 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#334 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
