Repository knative-extensions/eventing-istio, pull requests merged in 2024-09, with the labels that each got.

#486 Migrate to kube_codegen.sh
  hack/update-codegen.sh
Labels: approved, size/S, lgtm

#490 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#492 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#494 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#497 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#500 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#501 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#504 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#503 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#505 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm, skip-review

#509 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#512 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#513 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#515 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: size/L, skip-review

#514 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#516 [Automated] Update eventing-istio-eventing-kafka-broker nightly
  third_party/eventing-kafka-broker-latest/eventing-kafka-broker.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-channel.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-controller.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-sink.yaml
  third_party/eventing-kafka-broker-latest/eventing-kafka-source.yaml
Labels: approved, size/L, lgtm, skip-review

#517 [Automated] Update eventing-istio-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review
